In [8]:
# operasi penjumlahan vektor
# menggunakan list

a = [1, 2, 3, 3]
b = [5, 1, 2, 6]

def jumlah(a, b):
    c = [0] * len(a)
    for i in range(len(a)):
        c[i] = a[i] + b[i]
    return c

In [10]:
# tipe data dari numpy -> np.array
import numpy as np

a = [1,2,3,4]
b = [6,4,2,7]
np_a = np.array(a)
np_b = np.array(b)

In [13]:
a + b

[1, 2, 3, 4, 6, 4, 2, 7]

In [14]:
np_a + np_b

array([ 7,  6,  5, 11])

In [19]:
# CEK PERFORMA
a = [1] * 1000
b = [2] * 1000

In [20]:
%timeit jumlah(a,b)

72.9 µs ± 1.04 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [21]:
np_a = np.array(a)
np_b = np.array(b)

%timeit np_a + np_b

1.24 µs ± 88.9 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [23]:
# contoh array

a1d = [1,2,3,4,5]
a1d = np.array(a1d)
a1d

array([1, 2, 3, 4, 5])

In [24]:
a2d = [[1,3],[5,4],[7,8]]
a2d = np.array(a2d)
a2d

array([[1, 3],
       [5, 4],
       [7, 8]])

In [25]:
a2d = [[1,3],[5,4,5],[7,8]]
a2d = np.array(a2d)
a2d

C:\Users\afifa\AppData\Local\Temp\ipykernel_7128\3317907818.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  a2d = np.array(a2d)


array([list([1, 3]), list([5, 4, 5]), list([7, 8])], dtype=object)

In [30]:
a = [1,2,3,4,5.4, 'a']
a

[1, 2, 3, 4, 5.4, 'a']

In [31]:
a = np.array(a)
a

array(['1', '2', '3', '4', '5.4', 'a'], dtype='<U32')

In [33]:
A = [[1,3],[5,4],[7,8]]
A = np.array(A)
A

array([[1, 3],
       [5, 4],
       [7, 8]])

In [35]:
A[2][1]

8

In [36]:
A[2,1]

8

In [37]:
# memanggil baris
A[1]

array([5, 4])

In [38]:
A[1, :]

array([5, 4])

In [39]:
# memanggil kolom
A[:, 0]

array([1, 5, 7])

In [54]:
# special array
np.ones((10, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [44]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [56]:
np.empty(10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [48]:
np.arange(1,6, 0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5])

In [53]:
np.linspace(1, 10, 100)

array([ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
        1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182,
        1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
        2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273,
        2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
        3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364,
        3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
        4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455,
        4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
        5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545,
        5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
        6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636,
        6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
        6.90909091,  7.        ,  7.09090909,  7.18181818,  7.27

In [57]:
A = [[1,3],[5,4],[7,8]]
A = np.array(A)
A

array([[1, 3],
       [5, 4],
       [7, 8]])

In [58]:
A.ndim

2

In [59]:
A.shape

(3, 2)

In [60]:
A.size

6

In [61]:
a = [2,3,1,6,5,7,5,6]
a = np.array(a)
a

array([2, 3, 1, 6, 5, 7, 5, 6])

In [63]:
a.reshape((2,4))

array([[2, 3, 1, 6],
       [5, 7, 5, 6]])

In [65]:
a.reshape((2,4)).T

array([[2, 5],
       [3, 7],
       [1, 5],
       [6, 6]])

In [67]:
a.reshape((4,2))

array([[2, 3],
       [1, 6],
       [5, 7],
       [5, 6]])

In [68]:
a = [2,3,1,6,5,7,5,6]
a = np.array(a)
a

array([2, 3, 1, 6, 5, 7, 5, 6])

In [71]:
a[np.newaxis]

array([[2, 3, 1, 6, 5, 7, 5, 6]])

In [72]:
a[:,np.newaxis]

array([[2],
       [3],
       [1],
       [6],
       [5],
       [7],
       [5],
       [6]])

In [74]:
a

array([2, 3, 1, 6, 5, 7, 5, 6])

In [77]:
np.expand_dims(a, axis=1).shape

(8, 1)

In [78]:
a.shape

(8,)

Querying

In [79]:
mat = [[5,4,3,8,2], [4,6,3,7,4], [1,6,4,5,6]]
mat = np.array(mat)
mat

array([[5, 4, 3, 8, 2],
       [4, 6, 3, 7, 4],
       [1, 6, 4, 5, 6]])

In [83]:
mat[1:2, -2:]

array([[7, 4]])

In [84]:
mat > 4

array([[ True, False, False,  True, False],
       [False,  True, False,  True, False],
       [False,  True, False,  True,  True]])

In [85]:
mat[mat > 4]

array([5, 8, 6, 7, 6, 5, 6])

In [86]:
mahasiswa = np.array(['Afif', 'Fahmi', 'Danu', 'Raka'])
nilai = np.array([98.7, 75.3, 53.4, 45.2])

In [90]:
nilai < 60

array([False, False,  True,  True])

In [93]:
kondisi = nilai < 60
mahasiswa[kondisi]

array(['Danu', 'Raka'], dtype='<U5')

In [103]:
A = np.array([[1,2], [3,4]])
B = np.array([[6,5], [2,7]])
c = np.array([1,2])

In [95]:
A

array([[1, 2],
       [3, 4]])

In [96]:
B

array([[6, 5],
       [2, 7]])

In [105]:
A+B

array([[ 7,  7],
       [ 5, 11]])

In [106]:
A*B

array([[ 6, 10],
       [ 6, 28]])

In [107]:
# perkalian matriks secara aljabar linear
A @ B

array([[10, 19],
       [26, 43]])

In [108]:
A

array([[1, 2],
       [3, 4]])

In [116]:
A.mean(axis=0)

array([2., 3.])

In [121]:
np.random.random((2,3))

array([[0.14321969, 0.11525594, 0.08332918],
       [0.50464931, 0.5319203 , 0.37618385]])

In [123]:
C = np.arange(0,12)
C = C.reshape((4,3))

In [124]:
C

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [126]:
C.reshape((5,2))

ValueError: cannot reshape array of size 12 into shape (5,2)